MvcPL/ViewModels/QuadrocopterViewModel.cs
using System.ComponentModel.DataAnnotations;
using BLL.Interface.Entities;

namespace MvcPL.ViewModels
{
    public class QuadrocopterViewModel
    {
        public int Id { get; set; }
        [Display( Name = "Название")]
        public string Name { get; set; }
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Стоимость")]
        public double Cost { get; set; }

        public string ImagePath { get; set; }
        [Display(Name = "Артикль")]
        public int Article { get; set; }
        [Display(Name = "Дальность управления")]
        public int ControlDistance { get; set; }
        [Display(Name = "Наличие камеры")]
        public string CameraPresense { get; set; }
        [Display(Name = "Брэнд")]
        public string Brand { get; set; }
        [Display(Name = "Страна изготовитель")]
        public string MadeCountry { get; set; }
    }
}

MvcPL/Controllers/QuadrocopterController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Infrastructure;
using MvcPL.ViewModels;

namespace MvcPL.Controllers
{
   
    public class QuadrocopterController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly ICameraPresenceService _cameraPresenceService;
        private readonly ICountryService _countryService;
        private readonly IQuadrocopterService _quadrocopterService;

        public QuadrocopterController(IBrandService brandService, ICameraPresenceService cameraPresenceService,
            ICountryService countryService, IQuadrocopterService quadrocopterService)
        {
            _brandService = brandService;
            _cameraPresenceService = cameraPresenceService;
            _countryService = countryService;
            _quadrocopterService = quadrocopterService;
        }

        [QsAuthorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var countries = _countryService.GetAll();
            ViewBag.Countries = countries;

            var brands = _brandService.GetAll();
            ViewBag.Brands = brands;

            var camera = _cameraPresenceService.GetAll();
            ViewBag.CameraPres = camera;

            var quad = _quadrocopterService.GetById(id);
            ViewBag.Image = quad.ImagePath;
            var quadroModel = new CreateQuadrocopterViewModel()
            {
                Id = quad.Id,
                Article = quad.Article,
                BrandId = quad.Brand.Id,
                CameraPresenseId = quad.CameraPresense.Id,
                ControlDistance = quad.ControlDistance,
                Cost = quad.Cost,
                Description = quad.Description,
                MadeCountryId = quad.MadeCountry.Id,
                Name = quad.Name,
            };
            return View(quadroModel);
        }

        public ActionResult Edit(CreateQuadrocopterViewModel model)
        {
            return RedirectToRoute("/Home/Index");
        }

        public ActionResult ShowQuadrocopter(int quadroId)
        {
            var quadrocopter = _quadrocopterService.GetById(quadroId);
            
            return View(new QuadrocopterViewModel()
            {
                Article = quadrocopter.Article,
                Brand = quadrocopter.Brand.Name,
                CameraPresense = quadrocopter.CameraPresense.Type,
                ControlDistance = quadrocopter.ControlDistance,
                Cost = quadrocopter.Cost,
                Description = quadrocopter.Description,
                ImagePath = quadrocopter.ImagePath,
                MadeCountry = quadrocopter.MadeCountry.Name,
                Name = quadrocopter.Name
            });
        }

        [HttpPost]
        public ActionResult FilterQuadrocopers(FilterParametr[] Filter , int page = 1, int pageSize = 6)
        {
            var qadrocopters = this.Filter(Filter).ToList();
            var pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = qadrocopters.Count };
            qadrocopters = qadrocopters.Skip((page - 1) * pageSize).Take(pageSize).ToList();
           
            var model = new QuadrocopterPaginationModel
            {
                Quadrocopters = qadrocopters,
                PageInfo =pageInfo
            };
            return PartialView("QuadrocoptersView", model);
        }


        public ActionResult Index(int page = 1, int pageSize = 6)
        {
            var quadrocopters = _quadrocopterService.GetAll().ToList();
            var pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = quadrocopters.Count };
            quadrocopters = quadrocopters.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            var model = new QuadrocopterPaginationModel
            {
                Quadrocopters = quadrocopters,
                PageInfo = pageInfo
            };
            return PartialView("QuadrocoptersView", model);
        }
        
        [HttpGet]
        [QsAuthorize]
        public ActionResult AddQuadrocopter()
        {
            var countries = new SelectList(_countryService.GetAll(), "Id", "Name");
            ViewBag.Countries = countries;

            var brands = new SelectList(_brandService.GetAll(), "Id", "Name");
            ViewBag.Brands = brands;

            var camera = new SelectList(_cameraPresenceService.GetAll(), "Id", "Type");
            ViewBag.CameraPres = camera;
            return View(new CreateQuadrocopterViewModel());
        }

        [HttpPost]
        [QsAuthorize]
        public ActionResult AddQuadrocopter(CreateQuadrocopterViewModel model)
        {
            var quadrocopter = new Quadrocopter()
            {
                Article = model.Article,
                Brand = _brandService.GetById(model.BrandId),
                CameraPresense = _cameraPresenceService.GetById(model.CameraPresenseId),
                MadeCountry = _countryService.GetById(model.MadeCountryId),
                ControlDistance = model.ControlDistance,
                Cost = model.Cost,
                Description = model.Description,
                Name = model.Name
            };

            if (model.UploadedPreviewImage == null || model.UploadedPreviewImage.ContentLength <= 0)
                return RedirectToAction("NotFound", "Error");

            var path = Path.Combine(Server.MapPath("~/Uploads/Quadrocopters/"),
                Path.GetFileName(model.UploadedPreviewImage.FileName));
            model.UploadedPreviewImage.SaveAs(path);
            quadrocopter.ImagePath = "/Uploads/Quadrocopters/" + Path.GetFileName(model.UploadedPreviewImage.FileName);
            _quadrocopterService.Create(quadrocopter);

            return RedirectToAction("Index", "Home");
        }

        public IEnumerable<Quadrocopter> Filter(FilterParametr[] parametrs)
        {
            var allQuadrocopters = _quadrocopterService.GetAll().ToList();
            var quadrocoptersResult = new  List<Quadrocopter>();
            foreach (var parametr in parametrs)
            {
                switch (parametr.Critery)
                {
                     case "cameraPres":
                    {
                        quadrocoptersResult.AddRange(allQuadrocopters.Where(item=>item.CameraPresense.Type == parametr.Value));
                        break;
                    }
                    case "country":
                        {
                            quadrocoptersResult.AddRange(allQuadrocopters.Where(item => item.MadeCountry.Name == parametr.Value));
                            break;
                        }
                    case "brand":
                    {
                            quadrocoptersResult.AddRange(allQuadrocopters.Where(item => item.Brand.Name == parametr.Value));
                            break;
                    }

                }
            }

            return quadrocoptersResult.Distinct();
        }
    }
}

MvcPL/Views/Quadrocopter/AddQuadrocopter.cshtml
@model MvcPL.ViewModels.CreateQuadrocopterViewModel

@{
    ViewBag.Title = "AddQuadrocopter";
}

<h2>Добавление нового квадракоптера</h2>
<div class="container">
    @using (Html.BeginForm("AddQuadrocopter", "Quadrocopter", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BrandId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.BrandId, ViewBag.Brands as SelectList, new { @class = "form-control " })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CameraPresenseId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CameraPresenseId, ViewBag.CameraPres as SelectList, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MadeCountryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.MadeCountryId, ViewBag.Countries as SelectList, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Article, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Article, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Article, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Выберите изображение </label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.UploadedPreviewImage, new
               {
                   type = "file",
                   accept = "image/jpeg,image/png",
               })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ControlDistance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ControlDistance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ControlDistance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Создать" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Назад к списку", "Index")
    </div>
</div>

MvcPL/Views/Quadrocopter/Edit.cshtml
@using BLL.Interface.Entities
@model MvcPL.ViewModels.CreateQuadrocopterViewModel

@{
    ViewBag.Title = "Редактирование";
}

<h2>Редактирование @Model.Name</h2>
<div class="container-fluid">
    @using (Html.BeginForm("AddQuadrocopter", "Quadrocopter", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-horizontal">
            <hr />
            @Html.HiddenFor(model => model.Id)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BrandId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        var brandList = ViewBag.Brands as List<Brand>;
                    }
                    @if (brandList != null)
                    {
                        <select class="form-control" id="BrandId" name="BrandId">
                            @foreach (var item in brandList)
                            {
                                if (Model.BrandId == item.Id)
                                {
                                    <option selected value="@item.Id">@item.Name</option>
                                    continue;
                                }

                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CameraPresenseId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        var cameraPresenceList = ViewBag.CameraPres as List<CameraPresense>;
                    }
                    @if (cameraPresenceList != null)
                    {
                        <select class="form-control" id="CameraPresenseId" name="CameraPresenseId">
                            @foreach (var item in cameraPresenceList)
                            {
                                if (Model.CameraPresenseId == item.Id)
                                {
                                    <option selected value="@item.Id">@item.Type</option>
                                    continue;
                                }

                                <option value="@item.Id">@item.Type</option>
                            }
                        </select>
                    }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MadeCountryId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        var selectList = ViewBag.Countries as List<Country>;
                    }
                    @if (selectList != null)
                    {
                        <select class="form-control" id="MadeCountryId" name="MadeCountryId">
                            @foreach (var item in selectList)
                            {
                                if (Model.MadeCountryId == item.Id)
                                {
                                    <option selected value="@item.Id">@item.Name</option>
                                    continue;
                                }

                                <option value="@item.Id">@item.Name</option>
                            }
                        </select>
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Article, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Article, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Article, "", new { @class = "text-danger" })
                </div>
            </div>
            @if ((string)ViewBag.Image == null)
            {


            }
            else
            {
                <div class="form-group">
                    <label class="control-label col-md-2">Выберите изображение </label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.UploadedPreviewImage, new
                        {
                            type = "file",
                            accept = "image/jpeg,image/png",
                        })
                    </div>
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(model => model.ControlDistance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ControlDistance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ControlDistance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Назад к списку", "Index")
    </div>
</div>

MvcPL/Views/Quadrocopter/ShowQuadrocopter.cshtml
@model MvcPL.ViewModels.QuadrocopterViewModel

@{
    ViewBag.Title = @Model.Name;
}

<h2>@Model.Name</h2>

<div>
    <h4>Quadrocopter</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4">
                @if (Model.ImagePath != null)
                {
                    <img class="img img-responsive"  src="@Model.ImagePath" alt=""/>

                }
                else
                {
                    <img src="http://placehold.it/600x340" class="img img-responsive"  alt="" />
                }
                
            </div>
            <div class="col-xs-12 col-md-8 text-left" style="vertical-align:central">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Cost)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Cost) у.е. 
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Article)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Article)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Brand)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Brand)
                    </dd>
                    
                    <dt>
                        @Html.DisplayNameFor(model => model.MadeCountry)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MadeCountry)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CameraPresense)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CameraPresense)
                    </dd>

                    <dt>
                        <p>@Html.DisplayNameFor(model => model.ControlDistance)</p>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ControlDistance)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-info">
                <h3><b>Описание</b></h3>
                <p class="text-info">
                    @Model.Description
                </p>
            </div>
        </div>
    </div>
</div>
<p>
    @*TODO @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
   <a href="/Busket/AddToBusket/?userName=@User.Identity.Name&quadrocopterId=@Model.Id"></a>
    @Html.ActionLink("На главную", "Index", "Home")
</p>